<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-02-15 15:26
=======
# Generated by Django 3.1.6 on 2021-02-21 18:58
>>>>>>> 073f076 (Poprawienie modeli)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
<<<<<<< HEAD
                ('adres_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('wojewodztwo', models.CharField(max_length=50)),
                ('miejscowosc', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('numer_domu', models.IntegerField()),
                ('kod_pocztowy', models.CharField(default=None, max_length=50)),
                ('adres_poczatkowy', models.CharField(max_length=50)),
                ('adres_koncowy', models.CharField(max_length=50)),
                ('adres_spotkania', models.CharField(max_length=50)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo', models.CharField(max_length=50, null=True)),
                ('miejscowosc', models.CharField(max_length=50, null=True)),
                ('ulica', models.CharField(max_length=50, null=True)),
                ('numer_domu', models.IntegerField(null=True)),
>>>>>>> 073f076 (Poprawienie modeli)
            ],
        ),
        migrations.CreateModel(
            name='Ocenianie',
            fields=[
<<<<<<< HEAD
                ('ocena_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('punkt', models.CharField(choices=[('1', 'Bardzo Zle'), ('2', 'Zle'), ('3', 'Umiarkowany'), ('4', 'Dobrze'), ('5', 'Bardzo Dobrze')], max_length=60)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkt', models.CharField(choices=[('1', 'Bardzo Zle'), ('2', 'Zle'), ('3', 'Umiarkowany'), ('4', 'Dobrze'), ('5', 'Bardzo Dobrze')], max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('czas_odjazdu', models.TimeField(null=True)),
                ('czas_dojazdu', models.TimeField(null=True)),
                ('ilosc_miejsc', models.IntegerField(null=True)),
                ('cena', models.IntegerField(null=True)),
                ('komentarz', models.CharField(max_length=100, null=True)),
                ('rodzaj_ofert', models.CharField(choices=[('1', 'Pasazer'), ('2', 'Kierowca')], max_length=50, null=True)),
>>>>>>> 073f076 (Poprawienie modeli)
            ],
        ),
        migrations.CreateModel(
            name='Oferty',
            fields=[
                ('oferty_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('czas_odjazdu', models.TimeField()),
                ('ilosc_miejsc', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('komentarz', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
<<<<<<< HEAD
                ('role_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pasazer', models.BooleanField(default=False)),
                ('kierowca', models.BooleanField(default=False)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasazer', models.BooleanField(default=False, null=True)),
                ('kierowca', models.BooleanField(default=False, null=True)),
>>>>>>> 073f076 (Poprawienie modeli)
            ],
        ),
        migrations.CreateModel(
            name='Trasa',
            fields=[
<<<<<<< HEAD
                ('trasa_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adres_koncowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_kon', to='MainApp.adres')),
                ('adres_poczatkowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_pocz', to='MainApp.adres')),
                ('adres_spotkania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_spot', to='MainApp.adres')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, null=True)),
                ('adres_koncowy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adres_kon', to='MainApp.adres')),
                ('adres_poczatkowy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adres_pocz', to='MainApp.adres')),
                ('adres_spotkania', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adres_spot', to='MainApp.adres')),
>>>>>>> 073f076 (Poprawienie modeli)
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('uzytkownik_imie', models.CharField(max_length=50)),
                ('uzytkownik_nazwisko', models.CharField(max_length=50)),
                ('uzytkownik_telefon', models.IntegerField()),
                ('uzytkownik_mail', models.EmailField(max_length=100)),
                ('ocena_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.ocenianie')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.role')),
                ('trasa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.trasa')),
                ('uzytkownik', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trasaoferty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.oferty')),
                ('trasa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.trasa')),
            ],
        ),
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.IntegerField()),
                ('oferty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.oferty')),
                ('uzytkownik', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.uzytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='oferty',
            name='trasa_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainApp.trasa'),
        ),
        migrations.AddField(
            model_name='oferty',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.uzytkownik'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.ocenianie')),
                ('oferty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.oferty')),
=======
                ('uzytkownik_imie', models.CharField(max_length=50, null=True)),
                ('uzytkownik_nazwisko', models.CharField(max_length=50, null=True)),
                ('uzytkownik_telefon', models.IntegerField(null=True)),
                ('uzytkownik_mail', models.EmailField(max_length=100, null=True)),
                ('ocena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.ocenianie')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.role')),
                ('trasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.trasa')),
                ('uzytkownik', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, null=True)),
                ('model', models.IntegerField(null=True)),
                ('oferty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.oferty')),
                ('uzytkownik', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.uzytkownicy')),
>>>>>>> 073f076 (Poprawienie modeli)
            ],
        ),
        migrations.AddField(
            model_name='oferty',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.uzytkownicy'),
        ),
    ]
