# Generated by Django 3.1.5 on 2021-01-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres_id', models.IntegerField()),
                ('wojewodztwo', models.CharField(max_length=50)),
                ('miejscowosc', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('numer_domu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ocenianie',
            fields=[
                ('ocena_id', models.IntegerField(primary_key=True, serialize=False)),
                ('punkt', models.CharField(choices=[('1', 'Bardzo Zle'), ('2', 'Zle'), ('3', 'Umiarkowany'), ('4', 'Dobrze'), ('5', 'Bardzo Dobrze')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pasazer', models.BooleanField(default=False)),
                ('kierowca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trasa',
            fields=[
                ('trasa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now=True)),
                ('adres_koncowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_kon', to='MainApp.adres')),
                ('adres_poczatkowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_pocz', to='MainApp.adres')),
                ('adres_spotkania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_spot', to='MainApp.adres')),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('uzytkownik_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uzytkownik_imie', models.CharField(max_length=50)),
                ('uzytkownik_nazwisko', models.CharField(max_length=50)),
                ('uzytkownik_telefon', models.IntegerField()),
                ('uzytkownik_mail', models.EmailField(max_length=100)),
                ('ocena_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.ocenianie')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.role')),
                ('trasa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.trasa')),
            ],
        ),
    ]
