# Generated by Django 3.1.4 on 2021-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210104_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='numer_domu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ocenianie',
            name='ocena_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trasa',
            name='trasa_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='uzytkownik_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
