# Generated by Django 3.1.5 on 2021-01-21 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0002_auto_20210108_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferty',
            old_name='uzytkownik_id',
            new_name='uzytkownik',
        ),
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='id',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='uzytkownik_id',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='uzytkownik',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adres_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
