# Generated by Django 3.1.5 on 2021-03-04 20:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0003_auto_20210222_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='arrival_home',
            field=models.CharField(max_length=50, verbose_name='Numer domu (Punkt docelowy)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='arrival_postcode',
            field=models.CharField(max_length=5, verbose_name='Kod pocztowy (Punkt docelowy)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='arrival_street',
            field=models.CharField(max_length=500, verbose_name='Ulica (Punkt docelowy)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='car_model',
            field=models.CharField(max_length=50, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Copmpleted'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='departure',
            field=models.DateTimeField(verbose_name='Data ta czas wyjazdu'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='departure_home',
            field=models.CharField(max_length=50, verbose_name='Numer domu (Punkt początkowy)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='departure_postcode',
            field=models.CharField(max_length=5, verbose_name='Kod pocztowy (Punkt początkowy)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='departure_street',
            field=models.CharField(max_length=500, verbose_name='Ulica (Punkt początkowy)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Ilość osób:'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='oferta.ad', verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Initial'), (2, 'Confirmed'), (3, 'Rejected')], default=1, verbose_name='Status'),
        ),
    ]
